//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgreementSignature
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgreementSignature
    {
        public int Id { get; set; }
        public int AgreementStatus { get; set; }
        public int RoleRequiredToSign { get; set; }
        public Nullable<System.DateTime> DateSigned { get; set; }
        public byte[] SignedBody { get; set; }
        public string SignedMimeType { get; set; }
        public bool IsExpired { get; set; }
        public int Agreement_Id { get; set; }
        public Nullable<int> District_Id { get; set; }
        public Nullable<int> Region_Id { get; set; }
        public Nullable<int> SignedForUser_Id { get; set; }
        public Nullable<int> SigningUser_Id { get; set; }
        public bool EmailReminderPending { get; set; }
    
        public virtual Agreement Agreement { get; set; }
        public virtual User SignedForUser { get; set; }
        public virtual User SigningUser { get; set; }
        public virtual District District { get; set; }
        public virtual Region Region { get; set; }
    }
}
