//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgreementSignature
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public District()
        {
            this.AgreementSignatures = new HashSet<AgreementSignature>();
        }
    
        public int Id { get; set; }
        public string DistrictCode { get; set; }
        public string Name { get; set; }
        public int SchoolType { get; set; }
        public string DistrictCommonName { get; set; }
        public int CountyCode { get; set; }
        public string CountyName { get; set; }
        public string CharteringAgencyCode { get; set; }
        public string CharteringAgencyName { get; set; }
        public string GeographicLEADistrictCode { get; set; }
        public string GeographicLEADistrictName { get; set; }
        public string NCESCode { get; set; }
        public string LocaleCode { get; set; }
        public string LocaleName { get; set; }
        public string FIPSCode { get; set; }
        public string REMCId { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string PhoneExt { get; set; }
        public string Fax { get; set; }
        public string FaxExt { get; set; }
        public string LeadAdminTitle { get; set; }
        public string LeadAdminFirstName { get; set; }
        public string LeadAdminLastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string MailingAddress { get; set; }
        public string MailingCity { get; set; }
        public string MailingState { get; set; }
        public string MailingZip { get; set; }
        public bool ImportedIntoCockpit { get; set; }
        public int Status { get; set; }
        public Nullable<int> ETLServer_Id { get; set; }
        public Nullable<int> ISD_Id { get; set; }
        public string CurrentSchoolYear { get; set; }
        public string DashboardSupportContact { get; set; }
        public string DashboardSupportEmail { get; set; }
        public string DashboardSupportPhone { get; set; }
        public string DashboardTrainingAndPlanningUrl { get; set; }
        public string DashboardTicketOrgDescription { get; set; }
        public string DashboardTicketAssignee { get; set; }
        public string DashboardTicketSecurityLevel { get; set; }
        public string DashboardProjectName { get; set; }
        public string DashboardIssueType { get; set; }
        public string DashboardMissingSchoolName { get; set; }
        public string DashboardDefaultClassroomView { get; set; }
        public string SFTPPasswordForDistrictCodeUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgreementSignature> AgreementSignatures { get; set; }
        public virtual ISD ISD { get; set; }
    }
}
