//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgreementSignature
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OperationsCockpitContext : DbContext
    {
        public OperationsCockpitContext()
            : base("name=OperationsCockpitContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agreement> Agreements { get; set; }
        public virtual DbSet<AgreementSignature> AgreementSignatures { get; set; }
        public virtual DbSet<ClaimSet> ClaimSets { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<ISD> ISDs { get; set; }
    }
}
